### ISSUE TITLE
PhpMemAdmin fatal error

### ISSUE THREAD

**Issue by jwaisner** [Bearsampp/Bearsampp#196]
```

Fatal error: Uncaught Clickalicious\Memcached\Exception: Awaited "STAT" but received "" in C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\vendor\clickalicious\memcached.php\lib\Clickalicious\Memcached\Client.php:2077 Stack trace: #0 C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\vendor\clickalicious\memcached.php\lib\Clickalicious\Memcached\Client.php(2254): Clickalicious\Memcached\Client->parseStatsResponse(Array) #1 C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\vendor\clickalicious\memcached.php\lib\Clickalicious\Memcached\Client.php(1060): Clickalicious\Memcached\Client->parseResponse('stats', '') #2 C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\vendor\clickalicious\memcached.php\lib\Clickalicious\Memcached\Client.php(1593): Clickalicious\Memcached\Client->send('stats', 'stats settings\r...') #3 C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\lib\Clickalicious\PhpMemAdmin\App.php(2107): Clickalicious\Memcached\Client->stats(' settings') #4 C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\lib\Clickalicious\PhpMemAdmin\App.php(1507): Clickalicious\PhpMemAdmin\App->getSettings(Array) #5 C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\lib\Clickalicious\PhpMemAdmin\App.php(1134): Clickalicious\PhpMemAdmin\App->getContent(1) #6 C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\web\index2.php(108): Clickalicious\PhpMemAdmin\App->render('/phpmemadmin/in...', Array) #7 C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\web\index.php(40): include_once('C:\\Users\\Jacob\\...') #8 {main} thrown in C:\Users\Jacob\Desktop\Bearsamp\apps\phpmemadmin\phpmemadmin0.1.0.41\vendor\clickalicious\memcached.php\lib\Clickalicious\Memcached\Client.php on line 2077
```

Noting that there is a newer version of [phpmemadmin (0.3.1)](https://github.com/clickalicious/phpmemadmin/archive/refs/tags/v0.3.1.zip) that may fix this but needs testing.

**Comment by N6REJ** [comment]
Lets remove phpmemadmin and replace it with https://github.com/wgalaxy/KvFront as a "tool"
